---
- name: this is Ansible Test File
  hosts: all
  gather_facts: yes

  tasks:
    - name: Display message
      ansible.builtin.debug:
        msg: "This is my First Playbook"

    - name: Print command
      command: hostname -f
      register: reg_cmd
      #delegate_to: localhost

    - name: print host name FQDN
      debug: 
        var: reg_cmd.stdout

    - name: Get container hostname
      command: hostname
      register: hostname_output

    - debug:
        msg: "Execution Environment Hostname: {{ hostname_output.stdout }}"

    - name: Get EE hostname
      delegate_to: localhost
      run_once: true
      shell: |
        python3 - <<EOF
        import socket
        print(socket.gethostname())
        EOF
      register: ee_hostname

    - debug:
        var: ee_hostname.stdout

